services:
  speckit:
    image: python:3.12-slim
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - UV_TOOL_DIR=/workspace/.speckit
      - UV_TOOL_BIN_DIR=/workspace/.speckit/bin
      - PATH=/workspace/.speckit/bin:/usr/local/bin:/usr/bin:/bin
